drop table if exists book;
drop table if exists account;
drop table if exists message;
drop table if exists tb_employee;

create table book (
	--id integer PRIMARY KEY,
	id bigint generated by default as identity,
	douban_id varchar(64) not null,
	title varchar(128) not null,
	url varchar(255),
	description varchar(255),
	owner_id bigint not null,
	onboard_date timestamp,
	status varchar(32) not null,
	borrower_id bigint null,
	borrow_date timestamp
);

create table account (
	--id integer PRIMARY KEY,
	id bigint generated by default as identity,
	name varchar(64) not null,
	email varchar(128),
	hash_password varchar(255)
);

create table message (
	--id integer PRIMARY KEY,
	id bigint generated by default as identity,
	receiver_id bigint null,
	message varchar(256),
	receive_date timestamp
);

CREATE TABLE IF NOT EXISTS tb_employee(
	--id integer PRIMARY KEY,
	id bigint generated by default as identity,
	code NVARCHAR2(64) , 			--员工编号
	name nvarchar2(64) not null,		--姓名
	duty nvarchar2(64),				--职务
	roler nvarchar2(64),				--角色
	phone nvarchar2(12),				--手机号码
	email nvarchar2(100)  not null,		--邮箱
	password nvarchar(100)  not null,
	family_addr nvarchar2(255),		--家庭住址
	remark nvarchar2(256) 				--备注
);

--原料信息表
CREATE TABLE IF NOT EXISTS tb_material(
	id bigint generated by default as identity, 
	mate_code NVARCHAR2(64) NOT NULL,	--原料编号
	mate_name nvarchar2(64),			--原料名称
	mate_gb_standard nvarchar2(256),	--规格
	mate_num_stock int(11),				--库存量
	mate_num_alarm int(11),				--告警阈值
	remark nvarchar2(256));				--备注

--产品表
CREATE TABLE IF NOT EXISTS tb_product(
	id bigint generated by default as identity,
	prod_code NVARCHAR2(64) NOT NULL, 	--编号
	prod_name nvarchar2(64),			--名称
	prod_gb_standard nvarchar2(256),	--规格
	prod_type nvarchar2(256),			--类别
	prod_num_stock int(11),				--库存量
	prod_num_alarm int(11),				--库存告警阈值
	prod_drawing_code nvarchar2(256),	--图纸编号
	remark nvarchar2(256));				--备注

--产品原料关系表
CREATE TABLE IF NOT EXISTS tb_ex_pm(
	id bigint generated by default as identity,
	prod_code NVARCHAR2(64) NOT NULL, 	--产品编号
	mate_code_name nvarchar2(64),		--原料编号
	mate_num_stock int(11),				--数量
	remark nvarchar2(256));				--备注
	

--员工信息表
CREATE TABLE IF NOT EXISTS tb_employee(
	id bigint generated by default as identity,
	em_code NVARCHAR2(64) NOT NULL, 	--员工编号
	em_name nvarchar2(64),				--姓名
	em_duty nvarchar2(64),				--职务
	em_roler nvarchar2(64),				--角色
	em_phone nvarchar2(12),				--手机号码
	em_email nvarchar2(64),				--邮箱
	em_family_addr nvarchar2(64),		--家庭住址
	remark nvarchar2(256));				--备注
		
--角色信息表
CREATE TABLE IF NOT EXISTS tb_roler(
	id bigint generated by default as identity,
	rl_code NVARCHAR2(64) NOT NULL, 	--角色编号
	rl_name nvarchar2(64),				--角色名称
	rl_priv nvarchar2(64),				--权限
	remark nvarchar2(256));				--备注	

--权限表
CREATE TABLE IF NOT EXISTS tb_priv(
	id bigint generated by default as identity,
	pv_code NVARCHAR2(64) NOT NULL, 	--权限id
	pv_name nvarchar2(64),				--名称
	pv_desc nvarchar2(256),				--描述
	remark nvarchar2(256));				--备注

--产品入库明细
CREATE TABLE IF NOT EXISTS tb_prod_instock_info(
	id bigint generated by default as identity,
	pis_code nvarchar2(64),				--入库序号
	prod_code NVARCHAR2(64) NOT NULL, 	--产品编号
	prod_name nvarchar2(64),			--产品名称(预留)
	prod_barcode nvarchar2(64),			--产品条码
	mate_barcode nvarchar2(1024),		--原料条码列表（一个产品会有多个原料）
	gb_standard nvarchar2(64),			--规格
	pis_date	timestamp,				--入库时间
	pis_count int(11),					--入库数量
	pis_em_code nvarchar2(64),			--入库人编号
	pis_receipt nvarchar2(64),			--入库单据号
	prod_cost int(11),					--产品成本（涉密字段）
	remark nvarchar2(256));				--备注

--原料入库明细
CREATE TABLE IF NOT EXISTS tb_mate_instock_info(
	id bigint generated by default as identity,
	mis_code nvarchar2(64),				--入库序号
	mate_code NVARCHAR2(64) NOT NULL, 	--原料编号
	mate_name nvarchar2(64),			--原料名称(预留)
	mate_barcode nvarchar2(64),			--原料条码
	gb_standard nvarchar2(64),			--规格
	purchase_datetime timestamp,			--进货日期
	purchase_em_code nvarchar2(64),		--进货人编号
	mis_date	timestamp,				--入库时间
	mis_count int(11),					--入库数量
	mis_em_code nvarchar2(64),			--入库人编号
	mis_receipt nvarchar2(64),			--入库单据号
	mate_price int(11),					--原料价格（涉密字段）
	mate_supplier_code nvarchar2(64),	--供应商编号
	remark nvarchar2(256));				--备注

--产品出库明细
CREATE TABLE IF NOT EXISTS tb_prod_outstock_info(
	id bigint generated by default as identity,
	pos_code nvarchar2(64),				--出库序号
	prod_code NVARCHAR2(64) NOT NULL, 	--产品编号
	prod_name nvarchar2(64),			--产品名称
	prod_barcode nvarchar2(64),			--产品条码
	mate_barcode nvarchar2(1024),		--原料条码列表（一个产品会有多个原料）
	gb_standard nvarchar2(64),			--规格
	pos_date	timestamp,				--出库时间
	pos_count int(11),					--出库数量
	pos_em_code nvarchar2(64),			--出库人编号
	pos_receipt nvarchar2(64),			--出库单据号
	pos_salesperson nvarchar2(64),		--业务员编号
	pos_customer nvarchar2(64),			--客户编号
	prod_cose int(11),					--产品成本（涉密字段）
	remark nvarchar2(256));				--备注

--原料出库明细
CREATE TABLE IF NOT EXISTS tb_mate_outstock_info(
	id bigint generated by default as identity,
	mos_code nvarchar2(64),				--出库序号
	mate_code NVARCHAR2(64) NOT NULL, 	--原料编号
	mate_name nvarchar2(64),			--原料名称
	mate_barcode nvarchar2(64),			--原料条码
	gb_standard nvarchar2(64),			--规格
	consumer_code nvarchar2(64),		--领用人编号
	mos_date	timestamp,				--出库时间
	mos_count int(11),					--出库数量
	mos_em_code nvarchar2(64),			--出库人编号
	mos_receipt nvarchar2(64),			--出库单据号
	remark nvarchar2(256));				--备注

--条码信息
CREATE TABLE IF NOT EXISTS tb_barcode(
	id bigint generated by default as identity,
	bar_code nvarchar2(64),				--条码编号
	bar_code_type NVARCHAR2(64) NOT NULL,--物料类别
	generate_date	timestamp,			--生成时间
	enabled_date	timestamp,			--启用时间
	read_times int(11),					--扫描次数
	remark nvarchar2(256));				--备注

--扫描枪信息
CREATE TABLE IF NOT EXISTS tb_bcreader(
	id bigint generated by default as identity,
	bcr_code nvarchar2(64),				--扫描枪编号
	bcr_location NVARCHAR2(64) NOT NULL,--扫描枪位置
	read_times	int(11),				--扫描次数
	enabled_date	timestamp,		    --启用时间
	remark nvarchar2(256));				--备注

--图纸信息
CREATE TABLE IF NOT EXISTS tb_drawing(
	id bigint generated by default as identity,
	drw_code nvarchar2(64),				--图纸编号
	drw_name NVARCHAR2(64) NOT NULL,	--图纸名称
	drw_designer	nvarchar2(64),		--设计师
	drw_date	timestamp,				--出图日期
	drw_prod	nvarchar2(64),			--产品编号
	remark nvarchar2(256));				--备注
	
--供应商信息表
CREATE TABLE IF NOT EXISTS tb_supplier(
	id bigint generated by default as identity,
	sp_code nvarchar2(64),				--供应商编号
	sp_name NVARCHAR2(64) NOT NULL,		--供应商名称
	sp_addr	nvarchar2(64),				--地址
	enabled_date	timestamp,		    --登记日期
	sp_contacter nvarchar2(64),			--联系人
	sp_contacter_phone nvarchar2(64),	--联系电话
	sales_person nvarchar2(64), 		--业务员
	remark nvarchar2(256));				--备注

--客户信息表
CREATE TABLE IF NOT EXISTS tb_customer(
	id bigint generated by default as identity,
	cust_code nvarchar2(64),			--客户编号
	cust_name NVARCHAR2(64) NOT NULL,	--客户名称
	cust_addr	nvarchar2(64),			--客户地址
	enabled_date	timestamp,		    --登记日期
	cust_contacter nvarchar2(64),		--联系人
	cust_contacter_phone nvarchar2(64),	--联系电话
	sales_person nvarchar2(64), 		--业务员
	remark nvarchar2(256));				--备注