drop table if exists account;
drop table if exists message;


create table account (
	id bigint generated by default as identity,
	name varchar(64) not null,
	email varchar(128),
	hash_password varchar(255),
	primary key (id)
);

create table message (
	id bigint generated by default as identity,
	receiver_id bigint null,
	message varchar(256),
	receive_date timestamp,
	primary key (id)
);

CREATE TABLE IF NOT EXISTS tb_employee(
    id bigint generated by default as identity,
    em_code NVARCHAR2(64) NOT NULL, 
    em_name nvarchar2(64),
    em_duty nvarchar2(64),
    em_roler nvarchar2(64),
    em_phone nvarchar2(12),
    em_email nvarchar2(64),
    em_family nvarchar2(64),
    remark nvarchar2(256)); 